name = "PyCon US Tutorial 3"
interpreter = "../bundle/micropython.mjs"

[files]
"./libthree.py" = ""
"./glue/udataclasses.py" = "./udataclasses.py"

[js_modules.main]
"./glue/uniforms.js" = "uniforms"
"https://cdn.jsdelivr.net/npm/three@v0.176.0/build/three.module.js" = "three"
"https://cdn.jsdelivr.net/npm/three@v0.176.0/examples/jsm/controls/OrbitControls.js" = "oc"
"https://cdn.jsdelivr.net/npm/stats-gl@3.6.0/dist/main.js" = "stats_gl"
