name = "PyCon US Tutorial 7"
interpreter = "../bundle/micropython.mjs"

[files]
"./libthree.py" = ""
"./perlin.py" = ""
"./glue/udataclasses.py" = "./udataclasses.py"

[js_modules.main]
"./glue/uniforms.js" = "uniforms"
"../bundle/three.js/build/three.module.js" = "three"
"../bundle/three.js/examples/jsm/controls/OrbitControls.js" = "oc"
"../bundle/stats-gl.js" = "stats_gl"
