name = "PyCon US Tutorial 1"

[files]
"./libthree.py" = ""

[js_modules.main]
"https://cdn.jsdelivr.net/npm/three@v0.176.0/build/three.module.js" = "three"
"https://cdn.jsdelivr.net/npm/three@v0.176.0/examples/jsm/controls/OrbitControls.js" = "oc"
"https://cdn.jsdelivr.net/npm/stats-gl@3.6.0/dist/main.js" = "stats_gl"
